Adicionada página básica de documentação. Melhorados Makefiles. Adicionado teste de Xlib.

diff --git a/project/Makefile b/project/Makefile
--- a/project/Makefile
+++ b/project/Makefile
@@ -10,13 +10,12 @@ DEBUG_LEVEL=$(shell grep "\#define[ \t]\+W_DEBUG_LEVEL[ \t]\+" conf/conf.h | gre
 ifeq ($(strip $(TARGET_TEST)),W_WEB)
 web: test_emcc shader_data make-web
 else ifeq ($(strip $(TARGET_TEST)),W_ELF)
-prog: test_cc shader_data make-prog
+prog: test_cc test_xlib shader_data make-prog
 else
 err:
 	$(error Invalid W_TARGET in conf/conf.h)
 endif
 make-prog:
-	echo ${DEBUG_LEVEL}
 	@if [ -e .error ]; then	rm .error; \
 	else make --no-print-directory -j ${CORES} -f prog.Makefile; fi
 make-web:
@@ -27,16 +26,16 @@ shader_data: src/weaver/vertex_interface.data\
 		src/weaver/fragment_interface_texture.data\
 		src/weaver/vertex_interface_texture.data
 src/weaver/vertex_interface.data: src/weaver/vertex_interface.glsl
-	cat src/weaver/vertex_interface.glsl | sed 's/^#line.*//' | \
+	@cat src/weaver/vertex_interface.glsl | sed 's/^#line.*//' | \
 	xxd -i > src/weaver/vertex_interface.data
 src/weaver/fragment_interface.data: src/weaver/fragment_interface.glsl
-	cat src/weaver/fragment_interface.glsl | sed 's/^#line.*//' | \
+	@cat src/weaver/fragment_interface.glsl | sed 's/^#line.*//' | \
 	xxd -i > src/weaver/fragment_interface.data
 src/weaver/fragment_interface_texture.data: src/weaver/fragment_interface_texture.glsl
-	cat src/weaver/fragment_interface_texture.glsl | sed 's/^#line.*//' | \
+	@cat src/weaver/fragment_interface_texture.glsl | sed 's/^#line.*//' | \
 	xxd -i > src/weaver/fragment_interface_texture.data
 src/weaver/vertex_interface_texture.data: src/weaver/vertex_interface_texture.glsl
-	cat src/weaver/vertex_interface_texture.glsl | sed 's/^#line.*//' | \
+	@cat src/weaver/vertex_interface_texture.glsl | sed 's/^#line.*//' | \
 	xxd -i > src/weaver/vertex_interface_texture.data
 clean:
 	rm -f *.o *.bc *~ .weaver/*.o .weaver/*.bc src/weaver/*.data
@@ -45,6 +44,7 @@ distclean: clean
 	rm -f ${PROG}
 	rm -rf web
 	rm -f .weaver/have_*
+test_xlib: .weaver/have_xlib
 test_cc: .weaver/have_cc
 .weaver/have_cc:
 	@echo -n "Testing GCC or CLANG........."
@@ -55,6 +55,21 @@ test_cc: .weaver/have_cc
 	else /bin/echo -e "\033[31mFAILED\033[m";\
 	touch .error;\
 	echo "ERROR: Install gcc or clang to run this command.";\
+	fi
+.weaver/have_xlib:
+	@echo -n "Testing Xlib................."
+	@echo "#include <X11/Xlib.h>" > .weaver/dummy.c
+	@echo "#include <X11/XKBlib.h>" >> .weaver/dummy.c
+	@echo "int main(void){ return 1; }" >> .weaver/dummy.c
+	@(gcc .weaver/dummy.c -o .weaver/a.out -lX11 &> /dev/null && \
+	touch .weaver/have_xlib) || \
+	(clang .weaver/dummy.c -o .weaver/a.out -lX11 &> /dev/null && \
+	touch .weaver/have_xlib) ||true
+	@if [ -e .weaver/have_xlib ]; then \
+	echo "OK";  \
+	else /bin/echo -e "\033[31mFAILED\033[m";\
+	touch .error;\
+	echo "ERROR: Install Xlib headers to run this command.";\
 	fi
 test_emcc: .weaver/have_emcc
 .weaver/have_emcc:
